version: 2

jobs:
  # The build job
  build_and_deploy:
    docker:
      - image: circleci/node:10.15.3
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - app-dependencies-{{ checksum "client/package.json" }}

      # Install dependencies and Test
      - run:
          name: Install dependencies and Test
          command: |
            yarn install:client
            yarn test:client:ci

      # Build Client
      - run:
          name: Build Client
          command: |
            CI="" yarn client:build

      # # Save Cache
      - save_cache:
          key: app-dependencies-{{ checksum "client/package.json" }}
          paths:
            - node_modules

      # Setup AWS CLI
      - run:
          name: Setup AWS CLI
          command: |
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade
            eb --version

      # Setup AWS Credentials
      - run:
          name: Setup AWS Credentials
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config

      # Deploy to EB
      - run:
          name: Deploy to EB
          command: |
            git add .
            git add -f ./client/build
            eb deploy --staged

workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - master
